### ISSUE TITLE
Awarder to Awardee History - FOREST

### ISSUE THREAD

**Issue by PixelOrange** [PixelOrange/MARS#14]
This feature should check to ensure that the same awarder has not given the same awardee a token anywhere in this submission. This feature could theoretically break if there are too many comments in the same submission.

WARNING: This feature is very expensive both to MARS and to reddit. It will take exponentially longer to complete based on how many comments are in the submission and it will check the entire submission every time a token is found. Consider only checking against the tree. Tree searching is also expensive, but much less so.

Each top level comment is called a root. Each reply to a top level comment is part of that comment's tree. To only check trees, use Awarder to Awardee History - TREE

**Comment by Snorrrlax** [comment]
I could've sworn I made an issue related to this, but maybe I just commented about it on reddit somewhere. Basically, I was under the impression that the best approach was to not allow user 1 to give user 2 more than one delta in a comment tree, but allow user 1 to give user 2 a second delta as part of a second comment tree, because different comment trees could suggest different aspects of the view.

Either way, it's rare for user 1 to award user 2 two deltas in separate comment trees, and if this is a lot easier for you, then maybe it's the best way to go for everyone? 

I'll have another look for when I wrote about this somewhere.

**Comment by PixelOrange** [comment]
I remember having that conversation with you but I didn't have it documented. Seeing as how we agree on the practical reasons and it's a cheaper solution I'm going to close this FOREST issue as abandoned and remove references to it from my code.

**Comment by PixelOrange** [comment]
Removed
