### ISSUE TITLE
Delta Queue

### ISSUE THREAD

**Issue by PixelOrange** [PixelOrange/MARS#22]
Delta queue is a queue on the wiki that will allow easy moderation of every delta awarded. All deltas will be listed and handled according to FIFO (First In, First Out). Delta queue should do the following:

- [x] Approve deltas (do nothing but remove them from the wiki page)

- [x] Remove deltas (tell deltabot to run the remove command, requires #8 to be completed)

Additional features can be added at a later date but to keep this issue small I am only allowing these two objectives for now.

**Comment by Snorrrlax** [comment]
I was thinking maybe DeltaBot could message the mods with a reminder when the list reaches a certain number of deltas (25+, for example). Not vital though.

**Comment by PixelOrange** [comment]
Good idea. I don't have any idea what the wiki page limit is so having something like that is probably wise.

**Comment by Snorrrlax** [comment]
Cool :)

Also, I notice the delta queue is written like this:

| Awardee | Comment | Action |
| --- | --- | --- |
|/u/user|[Link](%s)| [Approve](/message/compose/?to=%s&subject=%s&message=%s) \ [Reject](/message/compose/?to=%s&subject=%s&message=%s)|

I was wondering if it would be possible to have it like this:

| Awardee | Comment | Action |
| --- | --- | --- |
|/u/user|[This is a link to the delta comment, and the text of this delta comment goes here &#8710;](%s)| [Approve](/message/compose/?to=%s&subject=%s&message=%s) \ [Reject](/message/compose/?to=%s&subject=%s&message=%s)|

Which would probably make it an easier moderation tool to use, as some would be obvious approvals or removals without even clicking the link.

I ask this also because delta history pages you use [%s](%s\) in order to make the submission title the text of the link. For the delta queue page you use [Link](%s\), is it as simple as changing that to [%s](%s\) also? Sorry if that's naive of me :P

**Comment by PixelOrange** [comment]
Hey, you're learning how to read my code! Yay!

Yeah, I can do that.

**Comment by Snorrrlax** [comment]
Haha, cool! :)

**Comment by PixelOrange** [comment]
If you ever do go to edit code like that, though, don't forget the variable. The %s is just a hook that says "hey, I'm expecting a variable here".

I think you've done this before, but just in case you forgot. :)

**Comment by PixelOrange** [comment]
The Delta Queue now works as expected.
