### ISSUE TITLE
A detailed explanation of the delta system for our users.

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#27]
We currently have [a wiki page](http://www.reddit.com/r/changemyview/wiki/deltasystem) that explains some very basic (and perhaps outdated) information about our delta system. I'm not sure if this is already in progress, but I think we need a more detailed break-down of the entire process; what deltabot does, along with some general comments on why the delta system even exists. The latter can be contributed to by any mod, but the former should perhaps be laid out by the developer.

**Comment by PixelOrange** [comment]
Someone created a new page (and put it in the text of the first-time-delta message) [here](http://www.reddit.com/r/changemyview/wiki/deltabot). I updated that one today. It looks like the link you provided is a duplicate.

My suggestion here is to hide the one you linked and use the one I linked since mine uses the name of the bot as the page name. The way I've written the code it'll work like this:

bot name page - information about the bot
* tracker page - information about deltas
* queue page - the delta queue

or written out in link format:

/wiki/deltabot = information about the bot
/wiki/deltabot/tracker = information about deltas
/wiki/deltabot/queue = the delta queue

The reason I coded it this way is so that if you were to take this to another sub it would automatically build the pages in that format. wiki/deltasystem doesn't follow that format and would cause some segmentation in a clean sub.

Regarding technical details, I don't know how granular you want me to get.

Regarding the "why", that's all you haha.

**Comment by Snorrrlax** [comment]
Sorry, yeah, that was me. I remember now that I thought wiki/deltabot was a better place to host it anyway. 

I don't think it should explain in detail *how* DeltaBot does things, just a complete description of what those things are. But maybe it already contains everything users need to know.

I'm not sure what you mean by information about deltas?

Okay I'll get round to typing up the why at some point :)

**Comment by PixelOrange** [comment]
Sorry, was trying to be brief.

So, the tracker page will show every user who's ever gotten a delta with a link to their delta history and their most recent delta. The last link will obviously break if we remove a delta but that's a small price to pay, I think. There's not really a good way to roll back individual links like that.

**Comment by PixelOrange** [comment]
So do we need more info on what deltaBot does or can I assign this to you for the delta documentation portion?

**Comment by Snorrrlax** [comment]
Well I think it would be nice there was a description of everything the code is doing for people who don't know how to read it, but there's no rush. I added a part called "why deltas?" just the other day.

**Comment by PixelOrange** [comment]
I think this is done. Take a look at the wiki page and let me know if it's good enough for you.

**Comment by Snorrrlax** [comment]
Thanks, looks good to me!
