### ISSUE TITLE
Usernames are all lowercase in wiki pages.

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#42]
http://www.reddit.com/r/changemyview/wiki/user/uncletrustworthy 

This username should have two uppercase letters in it.

**Comment by PixelOrange** [comment]
I was aware of this when you made the last issue for the lowercase uers in the confirmation and was hoping you wouldn't notice that I didn't fix this.

I can fix it, but it's going to require me to pass some new information down through the functions and I don't wanna. But since you noticed I guess I will.

It's also like that on the tracker page.

**Comment by Snorrrlax** [comment]
Ah, sorry for the bother!

**Comment by PixelOrange** [comment]
Liar!

**Comment by PixelOrange** [comment]
Pretty sure I fixed it everywhere now. Let me know if there are any other issues.

The whole weird formatting due to names thing may happen, too. If you see that let me know so I can find someone to test against.
